version: '2'

services:
  flask:
    image: webapp-flask
    build:
      context: .
      dockerfile: Dockerfile-flask
    ports:
      - "5000:5000"
    volumes:
      - "./:/app"
      - uploads:/uploads
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
  nginx:
    image: webapp-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./app.conf:/etc/nginx/conf.d/app.conf"
    depends_on:
      - flask
  jenkins:
    image: jenkins/jenkins:2.190.1
    user: root
    ports:
        - "8080:8080"
        - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - uploads:/uploads
    depends_on:
      - flask

volumes:
    uploads:
